[profile.ci.fuzz]
runs = 10_000

[profile.default]
solc = "0.8.20"
optimizer = true
optimizer_runs = 10_000
via_ir = true
bytecode_hash = "none"

[profile.optimized]
optimizer_runs = 10_000
via_ir = true
bytecode_hash = "none"

[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"
#bnb_smart_chain = "${BSC_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
#arbitrum_one = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
base = "${BASE_RPC_URL}"
real = "${REAL_RPC_URL}"

goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon_mumbai = "${MUMBAI_RPC_URL}"
unreal = "${UNREAL_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
#bnb_smart_chain = { key = "${ETHERSCAN_BSC_KEY}" }
polygon = { key = "${ETHERSCAN_POLYGON_KEY}" }
#arbitrum_one = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
optimism = { key = "${ETHERSCAN_OPTIMISM_KEY}" }
base = { key = "${ETHERSCAN_BASE_KEY}" }
unreal = { key = "", url = "https://unreal.blockscout.com/api" }

[fmt]
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
